app:
    resource: "../src/Controller/"
    type:     annotation

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    defaults:
      _controller: App\Controller\DefaultController::indexAction
